//! Mission sub-module: goals, daily planning, and reviews.
//!
//! All persistence goes through [`StoragePort`] (`ObjectStore`) and all
//! AI work goes through [`AgentPort`] — never concrete adapters (ADR-010).

use crate::{ForgeEngine, events};
use chrono::{NaiveDate, Utc};
use rusvel_core::domain::*;
use rusvel_core::error::Result;
use rusvel_core::id::*;
use serde::{Deserialize, Serialize};

/// A prioritized daily plan generated by the mission agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DailyPlan {
    pub date: NaiveDate,
    pub tasks: Vec<Task>,
    pub focus_areas: Vec<String>,
    pub notes: String,
    pub metadata: serde_json::Value,
}

/// A periodic review summarizing accomplishments and next steps.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Review {
    pub period: Timeframe,
    pub accomplishments: Vec<String>,
    pub blockers: Vec<String>,
    pub insights: Vec<String>,
    pub next_actions: Vec<String>,
    pub metadata: serde_json::Value,
}

impl ForgeEngine {
    /// Generate a prioritized daily plan from current goals and recent activity.
    pub async fn mission_today(&self, session_id: &SessionId) -> Result<DailyPlan> {
        let goals = self.list_goals(session_id).await?;
        let since = Utc::now() - chrono::Duration::hours(24);
        let recent = self
            .events
            .query(EventFilter {
                session_id: Some(*session_id),
                since: Some(since),
                ..Default::default()
            })
            .await?;

        let goal_lines: Vec<String> = goals
            .iter()
            .map(|g| format!("- {} ({:?}): {}", g.title, g.timeframe, g.description))
            .collect();
        let event_lines: Vec<String> = recent
            .iter()
            .map(|e| format!("- [{}] {}", e.kind, e.payload))
            .collect();

        let prompt = format!(
            "Given these goals:\n{}\n\nAnd recent activity:\n{}\n\n\
             Generate a prioritized daily plan with 3-7 tasks. \
             Respond in JSON: {{\"tasks\": [{{\"title\": \"...\", \"priority\": \"High|Medium|Low\"}}], \
             \"focus_areas\": [\"...\"], \"notes\": \"...\"}}",
            goal_lines.join("\n"),
            if event_lines.is_empty() {
                "No recent activity.".into()
            } else {
                event_lines.join("\n")
            },
        );

        let config = AgentConfig {
            profile_id: None,
            session_id: *session_id,
            model: None,
            tools: vec![],
            instructions: Some("You are a mission planning agent. Return valid JSON only.".into()),
            budget_limit: Some(0.10),
            metadata: serde_json::json!({}),
        };
        let run_id = self.agent.create(config).await?;
        let output = self.agent.run(&run_id, Content::text(prompt)).await?;

        let raw_text = extract_text(&output.content);
        let text = strip_code_fences(&raw_text);
        let parsed: PlanResponse = serde_json::from_str(text).unwrap_or(PlanResponse {
            tasks: vec![TaskEntry {
                title: "Review and plan manually".into(),
                priority: "Medium".into(),
            }],
            focus_areas: vec!["Planning".into()],
            notes: text.to_string(),
        });

        let today = Utc::now().date_naive();
        let mut tasks = Vec::new();
        for e in &parsed.tasks {
            let priority = match e.priority.to_lowercase().as_str() {
                "urgent" => Priority::Urgent,
                "high" => Priority::High,
                "low" => Priority::Low,
                _ => Priority::Medium,
            };
            let task = Task {
                id: TaskId::new(),
                session_id: *session_id,
                goal_id: None,
                title: e.title.clone(),
                status: TaskStatus::Todo,
                due_at: None,
                priority,
                metadata: serde_json::json!({}),
            };
            self.storage
                .objects()
                .put("task", &task.id.to_string(), serde_json::to_value(&task)?)
                .await?;
            tasks.push(task);
        }

        let plan = DailyPlan {
            date: today,
            tasks,
            focus_areas: parsed.focus_areas,
            notes: parsed.notes,
            metadata: serde_json::json!({}),
        };
        self.events
            .emit(Event {
                id: EventId::new(),
                session_id: Some(*session_id),
                run_id: Some(run_id),
                source: EngineKind::Forge,
                kind: events::MISSION_PLAN_GENERATED.into(),
                payload: serde_json::to_value(&plan)?,
                created_at: Utc::now(),
                metadata: serde_json::json!({}),
            })
            .await?;
        Ok(plan)
    }

    /// Create a new goal and persist it.
    pub async fn set_goal(
        &self,
        session_id: &SessionId,
        title: String,
        description: String,
        timeframe: Timeframe,
    ) -> Result<Goal> {
        let goal = Goal {
            id: GoalId::new(),
            session_id: *session_id,
            title,
            description,
            timeframe,
            status: GoalStatus::Active,
            progress: 0.0,
            metadata: serde_json::json!({}),
        };
        self.storage
            .objects()
            .put("goal", &goal.id.to_string(), serde_json::to_value(&goal)?)
            .await?;
        self.events
            .emit(Event {
                id: EventId::new(),
                session_id: Some(*session_id),
                run_id: None,
                source: EngineKind::Forge,
                kind: events::MISSION_GOAL_CREATED.into(),
                payload: serde_json::to_value(&goal)?,
                created_at: Utc::now(),
                metadata: serde_json::json!({}),
            })
            .await?;
        Ok(goal)
    }

    /// List all goals for a session.
    pub async fn list_goals(&self, session_id: &SessionId) -> Result<Vec<Goal>> {
        let filter = ObjectFilter {
            session_id: Some(*session_id),
            ..Default::default()
        };
        Ok(self
            .storage
            .objects()
            .list("goal", filter)
            .await?
            .into_iter()
            .filter_map(|v| serde_json::from_value(v).ok())
            .collect())
    }

    /// Generate a review for the given period.
    pub async fn review(&self, session_id: &SessionId, period: Timeframe) -> Result<Review> {
        let goals = self.list_goals(session_id).await?;
        let hours = match &period {
            Timeframe::Day => 24,
            Timeframe::Week => 168,
            Timeframe::Month => 720,
            Timeframe::Quarter => 2160,
        };
        let since = Utc::now() - chrono::Duration::hours(hours);
        let recent = self
            .events
            .query(EventFilter {
                session_id: Some(*session_id),
                since: Some(since),
                ..Default::default()
            })
            .await?;

        let prompt = format!(
            "Review period ({:?}).\n\nGoals:\n{}\n\nEvents ({}):\n{}\n\n\
             Respond in JSON: {{\"accomplishments\": [...], \"blockers\": [...], \
             \"insights\": [...], \"next_actions\": [...]}}",
            period,
            goals
                .iter()
                .map(|g| format!("- {} ({:?}, {:.0}%)", g.title, g.status, g.progress * 100.0))
                .collect::<Vec<_>>()
                .join("\n"),
            recent.len(),
            recent
                .iter()
                .take(20)
                .map(|e| format!("- [{}] {}", e.kind, e.payload))
                .collect::<Vec<_>>()
                .join("\n"),
        );

        let config = AgentConfig {
            profile_id: None,
            session_id: *session_id,
            model: None,
            tools: vec![],
            instructions: Some("You are a review agent. Return valid JSON only.".into()),
            budget_limit: Some(0.10),
            metadata: serde_json::json!({}),
        };
        let run_id = self.agent.create(config).await?;
        let output = self.agent.run(&run_id, Content::text(prompt)).await?;

        let raw_text = extract_text(&output.content);
        let text = strip_code_fences(&raw_text);
        let parsed: ReviewResponse = serde_json::from_str(text).unwrap_or(ReviewResponse {
            accomplishments: vec!["Review data collected".into()],
            blockers: vec![],
            insights: vec![],
            next_actions: vec!["Complete manual review".into()],
        });

        let review = Review {
            period,
            accomplishments: parsed.accomplishments,
            blockers: parsed.blockers,
            insights: parsed.insights,
            next_actions: parsed.next_actions,
            metadata: serde_json::json!({}),
        };
        self.events
            .emit(Event {
                id: EventId::new(),
                session_id: Some(*session_id),
                run_id: Some(run_id),
                source: EngineKind::Forge,
                kind: events::MISSION_REVIEW_COMPLETED.into(),
                payload: serde_json::to_value(&review)?,
                created_at: Utc::now(),
                metadata: serde_json::json!({}),
            })
            .await?;
        Ok(review)
    }
}

#[derive(Deserialize)]
struct PlanResponse {
    tasks: Vec<TaskEntry>,
    focus_areas: Vec<String>,
    notes: String,
}
#[derive(Deserialize)]
struct TaskEntry {
    title: String,
    priority: String,
}
#[derive(Deserialize)]
struct ReviewResponse {
    accomplishments: Vec<String>,
    blockers: Vec<String>,
    insights: Vec<String>,
    next_actions: Vec<String>,
}

fn extract_text(content: &Content) -> String {
    content
        .parts
        .iter()
        .find_map(|p| {
            if let Part::Text(s) = p {
                Some(s.clone())
            } else {
                None
            }
        })
        .unwrap_or_default()
}

/// Strip markdown code fences (```json ... ```) from LLM output so we can parse the JSON.
fn strip_code_fences(text: &str) -> &str {
    let trimmed = text.trim();
    if let Some(rest) = trimmed.strip_prefix("```") {
        // Skip the language tag (e.g., "json") on the first line
        let rest = rest.strip_prefix("json").unwrap_or(rest);
        let rest = rest.trim_start_matches('\n');
        rest.strip_suffix("```").unwrap_or(rest).trim()
    } else {
        trimmed
    }
}
