//! Mission sub-module: goals, daily planning, and reviews.
//!
//! All persistence goes through [`StoragePort`] (`ObjectStore`) and all
//! AI work goes through [`AgentPort`] — never concrete adapters (ADR-010).

use crate::safety::CircuitState;
use crate::{ForgeEngine, events};
use chrono::{NaiveDate, Utc};
use rusvel_core::department::{RouteContribution, ToolContribution};
use rusvel_core::domain::*;
use rusvel_core::error::Result;
use rusvel_core::id::*;
use serde::{Deserialize, Serialize};

/// HTTP routes implemented by the host (`rusvel-api`) for session-scoped mission APIs.
pub fn forge_route_contributions_for_manifest() -> Vec<RouteContribution> {
    vec![
        RouteContribution {
            method: "GET".into(),
            path: "/api/sessions/{id}/mission/today".into(),
            description: "Generate today's prioritized mission plan for the session".into(),
        },
        RouteContribution {
            method: "GET".into(),
            path: "/api/sessions/{id}/mission/goals".into(),
            description: "List goals for the session".into(),
        },
        RouteContribution {
            method: "POST".into(),
            path: "/api/sessions/{id}/mission/goals".into(),
            description: "Create a new goal for the session".into(),
        },
        RouteContribution {
            method: "GET".into(),
            path: "/api/sessions/{id}/events".into(),
            description: "Query events for the session (includes forge mission and safety events)"
                .into(),
        },
        RouteContribution {
            method: "GET".into(),
            path: "/api/brief/latest".into(),
            description: "Return the most recently persisted executive brief for a session".into(),
        },
    ]
}

/// Declarative tool list for ADR-014 manifests (must match registered handlers in `dept-forge`).
pub fn mission_tool_contributions_for_manifest() -> Vec<ToolContribution> {
    vec![
        ToolContribution {
            name: "forge.mission.today".into(),
            description:
                "Generate today's prioritized mission plan from active goals and recent activity"
                    .into(),
            parameters_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "session_id": { "type": "string", "description": "Session UUID" }
                },
                "required": ["session_id"]
            }),
        },
        ToolContribution {
            name: "forge.mission.list_goals".into(),
            description: "List all goals for a session".into(),
            parameters_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "session_id": { "type": "string", "description": "Session UUID" }
                },
                "required": ["session_id"]
            }),
        },
        ToolContribution {
            name: "forge.mission.set_goal".into(),
            description: "Create a new goal for a session".into(),
            parameters_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "session_id": { "type": "string" },
                    "title": { "type": "string" },
                    "description": { "type": "string" },
                    "timeframe": { "type": "string", "enum": ["Day", "Week", "Month", "Quarter"] }
                },
                "required": ["session_id", "title", "description", "timeframe"]
            }),
        },
        ToolContribution {
            name: "forge.mission.review".into(),
            description: "Generate a periodic review (accomplishments, blockers, next actions)"
                .into(),
            parameters_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "session_id": { "type": "string" },
                    "period": { "type": "string", "enum": ["Day", "Week", "Month", "Quarter"] }
                },
                "required": ["session_id", "period"]
            }),
        },
        ToolContribution {
            name: "forge.persona.hire".into(),
            description:
                "Build an AgentConfig from a named Forge persona (for spawning a sub-agent)".into(),
            parameters_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "session_id": { "type": "string" },
                    "persona_name": { "type": "string", "description": "Persona name (e.g. CodeWriter, Reviewer)" }
                },
                "required": ["session_id", "persona_name"]
            }),
        },
    ]
}

/// A prioritized daily plan generated by the mission agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DailyPlan {
    pub date: NaiveDate,
    pub tasks: Vec<Task>,
    pub focus_areas: Vec<String>,
    pub notes: String,
    pub metadata: serde_json::Value,
}

/// A periodic review summarizing accomplishments and next steps.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Review {
    pub period: Timeframe,
    pub accomplishments: Vec<String>,
    pub blockers: Vec<String>,
    pub insights: Vec<String>,
    pub next_actions: Vec<String>,
    pub metadata: serde_json::Value,
}

impl ForgeEngine {
    /// Run a mission-planning or review LLM call with [`crate::safety::SafetyGuard`]:
    /// circuit check, budget check, concurrency slot, spend recording, and failure tracking.
    pub async fn run_agent_with_mission_safety(
        &self,
        session_id: SessionId,
        config: AgentConfig,
        prompt: Content,
    ) -> Result<AgentOutput> {
        self.safety.check_circuit()?;
        let est = config.budget_limit.unwrap_or(0.10);
        self.safety.check_budget(est)?;
        let _slot = self.safety.acquire_slot()?;
        let run_id = self.agent.create(config).await?;
        match self.agent.run(&run_id, prompt).await {
            Ok(output) => {
                self.safety.record_spend(output.cost_estimate);
                if let Some((spent, limit)) = self.safety.take_budget_warning_if_needed() {
                    let _ = self
                        .events
                        .emit(Event {
                            id: EventId::new(),
                            session_id: Some(session_id),
                            run_id: Some(run_id),
                            source: "forge".into(),
                            kind: events::SAFETY_BUDGET_WARNING.into(),
                            payload: serde_json::json!({
                                "spent": spent,
                                "limit": limit,
                                "threshold_ratio": 0.8
                            }),
                            created_at: Utc::now(),
                            metadata: serde_json::json!({}),
                        })
                        .await;
                }
                self.safety.record_success();
                Ok(output)
            }
            Err(e) => {
                if self.safety.record_failure() == CircuitState::Open {
                    let _ = self
                        .events
                        .emit(Event {
                            id: EventId::new(),
                            session_id: Some(session_id),
                            run_id: Some(run_id),
                            source: "forge".into(),
                            kind: events::SAFETY_CIRCUIT_OPEN.into(),
                            payload: serde_json::json!({"reason": "mission_agent_failed"}),
                            created_at: Utc::now(),
                            metadata: serde_json::json!({}),
                        })
                        .await;
                }
                Err(e)
            }
        }
    }

    /// Generate a prioritized daily plan from current goals and recent activity.
    pub async fn mission_today(&self, session_id: &SessionId) -> Result<DailyPlan> {
        let goals = self.list_goals(session_id).await?;
        let since = Utc::now() - chrono::Duration::hours(24);
        let recent = self
            .events
            .query(EventFilter {
                session_id: Some(*session_id),
                since: Some(since),
                ..Default::default()
            })
            .await?;

        let goal_lines: Vec<String> = goals
            .iter()
            .map(|g| format!("- {} ({:?}): {}", g.title, g.timeframe, g.description))
            .collect();
        let event_lines: Vec<String> = recent
            .iter()
            .map(|e| format!("- [{}] {}", e.kind, e.payload))
            .collect();

        let prompt = format!(
            "Given these goals:\n{}\n\nAnd recent activity:\n{}\n\n\
             Generate a prioritized daily plan with 3-7 tasks. \
             Respond in JSON: {{\"tasks\": [{{\"title\": \"...\", \"priority\": \"High|Medium|Low\"}}], \
             \"focus_areas\": [\"...\"], \"notes\": \"...\"}}",
            goal_lines.join("\n"),
            if event_lines.is_empty() {
                "No recent activity.".into()
            } else {
                event_lines.join("\n")
            },
        );

        let config = AgentConfig {
            profile_id: None,
            session_id: *session_id,
            model: None,
            tools: vec![],
            instructions: Some("You are a mission planning agent. Return valid JSON only.".into()),
            budget_limit: Some(0.10),
            metadata: serde_json::json!({}),
        };
        let output = self
            .run_agent_with_mission_safety(*session_id, config, Content::text(prompt))
            .await?;
        let run_id = output.run_id;

        let raw_text = extract_text(&output.content);
        let text = strip_code_fences(&raw_text);
        let parsed: PlanResponse = serde_json::from_str(text).unwrap_or(PlanResponse {
            tasks: vec![TaskEntry {
                title: "Review and plan manually".into(),
                priority: "Medium".into(),
            }],
            focus_areas: vec!["Planning".into()],
            notes: text.to_string(),
        });

        let today = Utc::now().date_naive();
        let mut tasks = Vec::new();
        for e in &parsed.tasks {
            let priority = match e.priority.to_lowercase().as_str() {
                "urgent" => Priority::Urgent,
                "high" => Priority::High,
                "low" => Priority::Low,
                _ => Priority::Medium,
            };
            let task = Task {
                id: TaskId::new(),
                session_id: *session_id,
                goal_id: None,
                title: e.title.clone(),
                status: TaskStatus::Todo,
                due_at: None,
                priority,
                metadata: serde_json::json!({}),
            };
            self.storage
                .objects()
                .put("task", &task.id.to_string(), serde_json::to_value(&task)?)
                .await?;
            tasks.push(task);
        }

        let plan = DailyPlan {
            date: today,
            tasks,
            focus_areas: parsed.focus_areas,
            notes: parsed.notes,
            metadata: serde_json::json!({}),
        };
        self.events
            .emit(Event {
                id: EventId::new(),
                session_id: Some(*session_id),
                run_id: Some(run_id),
                source: "forge".into(),
                kind: events::MISSION_PLAN_GENERATED.into(),
                payload: serde_json::to_value(&plan)?,
                created_at: Utc::now(),
                metadata: serde_json::json!({}),
            })
            .await?;
        Ok(plan)
    }

    /// Create a new goal and persist it.
    pub async fn set_goal(
        &self,
        session_id: &SessionId,
        title: String,
        description: String,
        timeframe: Timeframe,
    ) -> Result<Goal> {
        let goal = Goal {
            id: GoalId::new(),
            session_id: *session_id,
            title,
            description,
            timeframe,
            status: GoalStatus::Active,
            progress: 0.0,
            metadata: serde_json::json!({}),
        };
        self.storage
            .objects()
            .put("goal", &goal.id.to_string(), serde_json::to_value(&goal)?)
            .await?;
        self.events
            .emit(Event {
                id: EventId::new(),
                session_id: Some(*session_id),
                run_id: None,
                source: "forge".into(),
                kind: events::MISSION_GOAL_CREATED.into(),
                payload: serde_json::to_value(&goal)?,
                created_at: Utc::now(),
                metadata: serde_json::json!({}),
            })
            .await?;
        Ok(goal)
    }

    /// List all goals for a session.
    pub async fn list_goals(&self, session_id: &SessionId) -> Result<Vec<Goal>> {
        let filter = ObjectFilter {
            session_id: Some(*session_id),
            ..Default::default()
        };
        Ok(self
            .storage
            .objects()
            .list("goal", filter)
            .await?
            .into_iter()
            .filter_map(|v| serde_json::from_value(v).ok())
            .collect())
    }

    /// Generate a review for the given period.
    pub async fn review(&self, session_id: &SessionId, period: Timeframe) -> Result<Review> {
        let goals = self.list_goals(session_id).await?;
        let hours = match &period {
            Timeframe::Day => 24,
            Timeframe::Week => 168,
            Timeframe::Month => 720,
            Timeframe::Quarter => 2160,
        };
        let since = Utc::now() - chrono::Duration::hours(hours);
        let recent = self
            .events
            .query(EventFilter {
                session_id: Some(*session_id),
                since: Some(since),
                ..Default::default()
            })
            .await?;

        let prompt = format!(
            "Review period ({:?}).\n\nGoals:\n{}\n\nEvents ({}):\n{}\n\n\
             Respond in JSON: {{\"accomplishments\": [...], \"blockers\": [...], \
             \"insights\": [...], \"next_actions\": [...]}}",
            period,
            goals
                .iter()
                .map(|g| format!("- {} ({:?}, {:.0}%)", g.title, g.status, g.progress * 100.0))
                .collect::<Vec<_>>()
                .join("\n"),
            recent.len(),
            recent
                .iter()
                .take(20)
                .map(|e| format!("- [{}] {}", e.kind, e.payload))
                .collect::<Vec<_>>()
                .join("\n"),
        );

        let config = AgentConfig {
            profile_id: None,
            session_id: *session_id,
            model: None,
            tools: vec![],
            instructions: Some("You are a review agent. Return valid JSON only.".into()),
            budget_limit: Some(0.10),
            metadata: serde_json::json!({}),
        };
        let output = self
            .run_agent_with_mission_safety(*session_id, config, Content::text(prompt))
            .await?;
        let run_id = output.run_id;

        let raw_text = extract_text(&output.content);
        let text = strip_code_fences(&raw_text);
        let parsed: ReviewResponse = serde_json::from_str(text).unwrap_or(ReviewResponse {
            accomplishments: vec!["Review data collected".into()],
            blockers: vec![],
            insights: vec![],
            next_actions: vec!["Complete manual review".into()],
        });

        let review = Review {
            period,
            accomplishments: parsed.accomplishments,
            blockers: parsed.blockers,
            insights: parsed.insights,
            next_actions: parsed.next_actions,
            metadata: serde_json::json!({}),
        };
        self.events
            .emit(Event {
                id: EventId::new(),
                session_id: Some(*session_id),
                run_id: Some(run_id),
                source: "forge".into(),
                kind: events::MISSION_REVIEW_COMPLETED.into(),
                payload: serde_json::to_value(&review)?,
                created_at: Utc::now(),
                metadata: serde_json::json!({}),
            })
            .await?;
        Ok(review)
    }

    /// Cross-department daily digest: one LLM call per department (persona-mapped), then a strategist pass for summary + actions.
    pub async fn generate_brief(&self, session_id: &SessionId) -> Result<ExecutiveBrief> {
        let today = Utc::now().date_naive();
        let mut sections = Vec::new();

        for dept in BRIEF_DEPARTMENT_IDS {
            let section = match self.dept_brief_section(session_id, dept).await {
                Ok(s) => s,
                Err(e) => BriefSection {
                    department: (*dept).to_string(),
                    status: "red".into(),
                    highlights: vec![format!("Brief section failed: {e}")],
                    metrics: serde_json::json!({}),
                    metadata: Default::default(),
                },
            };
            sections.push(section);
        }

        let sections_json = serde_json::to_string(&sections).unwrap_or_else(|_| "[]".to_string());
        let strategist_prompt = format!(
            "You are an executive strategist. Here are department brief sections (JSON):\n{sections_json}\n\n\
             Write a 2–3 sentence executive summary and list the top 3–5 cross-cutting action items.\n\
             Respond with JSON only, no markdown fences: \
             {{\"summary\": \"...\", \"action_items\": [\"...\", \"...\"]}}"
        );

        let mut config = self.hire_persona("Architect", session_id)?;
        let base = config.instructions.clone().unwrap_or_default();
        config.instructions = Some(format!(
            "{base}\nYou synthesize executive briefs. Return valid JSON only."
        ));

        let output = self
            .run_agent_with_mission_safety(*session_id, config, Content::text(strategist_prompt))
            .await?;

        let raw = extract_text(&output.content);
        let text = strip_code_fences(&raw);
        let parsed: StrategistBriefResponse =
            serde_json::from_str(text).unwrap_or(StrategistBriefResponse {
                summary: "Review department sections below for details.".into(),
                action_items: vec!["Align on priorities across departments".into()],
            });

        let brief = ExecutiveBrief {
            id: uuid::Uuid::now_v7().to_string(),
            date: today,
            sections,
            summary: parsed.summary,
            action_items: parsed.action_items,
            created_at: Utc::now(),
            metadata: Default::default(),
        };

        self.persist_executive_brief(session_id, &brief).await;

        Ok(brief)
    }

    /// Most recently generated brief for this session (object store), if any.
    pub async fn latest_brief(&self, session_id: &SessionId) -> Result<Option<ExecutiveBrief>> {
        const KIND: &str = "executive_brief";
        let rows = self
            .storage
            .objects()
            .list(
                KIND,
                ObjectFilter {
                    session_id: Some(*session_id),
                    limit: Some(64),
                    ..Default::default()
                },
            )
            .await?;

        let mut parsed: Vec<ExecutiveBrief> = rows
            .into_iter()
            .filter_map(|v| {
                let stored: ExecutiveBriefStored = serde_json::from_value(v).ok()?;
                Some(stored.brief)
            })
            .collect();
        parsed.sort_by(|a, b| b.created_at.cmp(&a.created_at));
        Ok(parsed.into_iter().next())
    }

    async fn persist_executive_brief(&self, session_id: &SessionId, brief: &ExecutiveBrief) {
        const KIND: &str = "executive_brief";
        let stored = ExecutiveBriefStored {
            session_id: *session_id,
            brief: brief.clone(),
        };
        let value = match serde_json::to_value(&stored) {
            Ok(v) => v,
            Err(e) => {
                tracing::warn!(error = %e, "executive brief serialization failed");
                return;
            }
        };
        if let Err(e) = self.storage.objects().put(KIND, &brief.id, value).await {
            tracing::warn!(error = %e, "failed to persist executive brief");
            return;
        }

        let _ = self
            .events
            .emit(Event {
                id: EventId::new(),
                session_id: Some(*session_id),
                run_id: None,
                source: "forge".into(),
                kind: events::BRIEF_GENERATED.into(),
                payload: serde_json::json!({
                    "brief_id": brief.id,
                    "date": brief.date,
                }),
                created_at: Utc::now(),
                metadata: serde_json::json!({}),
            })
            .await;
    }

    async fn dept_brief_section(
        &self,
        session_id: &SessionId,
        department_id: &str,
    ) -> Result<BriefSection> {
        let persona_name = persona_for_department(department_id);
        let mut config = self.hire_persona(persona_name, session_id)?;
        let base = config.instructions.clone().unwrap_or_default();
        config.instructions = Some(format!(
            "{base}\n\nYou are reporting a concise snapshot for the **{department_id}** department.\n\
             Respond with JSON only, no markdown fences: \
             {{\"status\":\"green|yellow|red\",\"highlights\":[\"...\",\"...\"],\"metrics\":{{}}}}\n\
             Cover: What happened today (or in the last 24h) relevant to this department? \
             Key metrics or signals? What needs attention?"
        ));

        let output = self
            .run_agent_with_mission_safety(
                *session_id,
                config,
                Content::text(format!(
                    "Produce today's department brief JSON for `{department_id}`."
                )),
            )
            .await?;

        let raw = extract_text(&output.content);
        let text = strip_code_fences(&raw);
        let parsed: DeptBriefJson = serde_json::from_str(text).unwrap_or(DeptBriefJson {
            status: "yellow".into(),
            highlights: vec![truncate_highlight(&raw)],
            metrics: serde_json::json!({}),
        });

        Ok(BriefSection {
            department: department_id.to_string(),
            status: normalize_status(&parsed.status),
            highlights: if parsed.highlights.is_empty() {
                vec![truncate_highlight(&raw)]
            } else {
                parsed.highlights
            },
            metrics: parsed.metrics,
            metadata: Default::default(),
        })
    }
}

/// Departments included in the executive brief (aligned with the default registry).
const BRIEF_DEPARTMENT_IDS: &[&str] = &[
    "forge", "code", "harvest", "content", "gtm", "finance", "growth", "distro", "legal",
    "support", "infra", "product",
];

fn persona_for_department(dept_id: &str) -> &'static str {
    match dept_id {
        "code" => "CodeWriter",
        "content" | "growth" | "distro" | "gtm" => "ContentWriter",
        "harvest" | "finance" | "legal" => "Researcher",
        "support" => "Documenter",
        "forge" | "infra" | "product" => "Architect",
        _ => "Architect",
    }
}

fn normalize_status(s: &str) -> String {
    match s.to_lowercase().as_str() {
        "green" | "yellow" | "red" => s.to_lowercase(),
        _ => "yellow".into(),
    }
}

fn truncate_highlight(s: &str) -> String {
    let t = s.trim();
    let mut out: String = t.chars().take(400).collect();
    if t.chars().count() > 400 {
        out.push('…');
    }
    out
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ExecutiveBriefStored {
    session_id: SessionId,
    #[serde(flatten)]
    brief: ExecutiveBrief,
}

#[derive(Deserialize)]
struct DeptBriefJson {
    status: String,
    highlights: Vec<String>,
    metrics: serde_json::Value,
}

#[derive(Deserialize)]
struct StrategistBriefResponse {
    summary: String,
    action_items: Vec<String>,
}

#[derive(Deserialize)]
struct PlanResponse {
    tasks: Vec<TaskEntry>,
    focus_areas: Vec<String>,
    notes: String,
}
#[derive(Deserialize)]
struct TaskEntry {
    title: String,
    priority: String,
}
#[derive(Deserialize)]
struct ReviewResponse {
    accomplishments: Vec<String>,
    blockers: Vec<String>,
    insights: Vec<String>,
    next_actions: Vec<String>,
}

fn extract_text(content: &Content) -> String {
    content
        .parts
        .iter()
        .find_map(|p| {
            if let Part::Text(s) = p {
                Some(s.clone())
            } else {
                None
            }
        })
        .unwrap_or_default()
}

/// Strip markdown code fences (```json ... ```) from LLM output so we can parse the JSON.
fn strip_code_fences(text: &str) -> &str {
    let trimmed = text.trim();
    if let Some(rest) = trimmed.strip_prefix("```") {
        // Skip the language tag (e.g., "json") on the first line
        let rest = rest.strip_prefix("json").unwrap_or(rest);
        let rest = rest.trim_start_matches('\n');
        rest.strip_suffix("```").unwrap_or(rest).trim()
    } else {
        trimmed
    }
}
