//! Composition root for RUSVEL.
//!
//! Wires all adapter crates into engine ports and dispatches to the
//! appropriate surface: CLI (subcommand), MCP (--mcp flag), or API
//! (default — starts the web server).
//!
//! ## Department-as-App (ADR-014)
//!
//! Departments are registered via [`boot::boot_departments()`] which
//! reads manifests, validates dependencies, and calls `register()` in
//! order. The generated [`DepartmentRegistry`] replaces the TOML-based
//! registry for the API server.

mod boot;

use std::io::IsTerminal;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use anyhow::Result;
use async_trait::async_trait;
use chrono::Utc;
use clap::Parser;
use tracing_subscriber::EnvFilter;

use forge_engine::ForgeEngine;
use rusvel_agent::AgentRuntime;
use rusvel_api::AppState;
use rusvel_auth::InMemoryAuthAdapter;
use rusvel_cli::Cli;
use rusvel_config::TomlConfig;
use rusvel_core::domain::*;
use rusvel_core::id::AgentProfileId;
use rusvel_core::id::SessionId;
use rusvel_core::ports::{
    ConfigPort, DeployPort, EmbeddingPort, JobPort, SessionPort, StoragePort, TerminalPort,
    VectorStorePort,
};
use uuid::Uuid;
// DepartmentRegistry now generated by boot::boot_departments() (ADR-014)
use rusvel_db::Database;
use rusvel_embed::FastEmbedAdapter;
use rusvel_event::EventBus;
use rusvel_llm::ClaudeCliProvider;
use rusvel_mcp::RusvelMcp;
use rusvel_memory::MemoryStore;
use rusvel_tool::ToolRegistry;
use rusvel_terminal::TerminalManager;
use rusvel_vector::LanceVectorStore;

// ════════════════════════════════════════════════════════════════════
//  Embedded frontend assets (built from frontend/build/)
// ════════════════════════════════════════════════════════════════════

#[derive(rust_embed::Embed)]
#[folder = "../../frontend/build/"]
#[prefix = ""]
struct FrontendAssets;

/// Extract embedded frontend assets to a temporary directory.
/// Returns the path to the directory containing the extracted files.
fn extract_embedded_frontend() -> Option<PathBuf> {
    let dir = std::env::temp_dir().join("rusvel-frontend");
    if let Err(e) = std::fs::create_dir_all(&dir) {
        tracing::warn!("Failed to create temp frontend dir: {e}");
        return None;
    }

    let mut count = 0usize;
    for path in FrontendAssets::iter() {
        if let Some(content) = FrontendAssets::get(&path) {
            let out = dir.join(path.as_ref());
            if let Some(parent) = out.parent()
                && let Err(e) = std::fs::create_dir_all(parent)
            {
                tracing::warn!("Failed to create dir {}: {e}", parent.display());
                continue;
            }
            if let Err(e) = std::fs::write(&out, content.data.as_ref()) {
                tracing::warn!("Failed to write {}: {e}", out.display());
                continue;
            }
            count += 1;
        }
    }

    if count > 0 && dir.join("index.html").exists() {
        tracing::info!(
            "Extracted {count} embedded frontend files to {}",
            dir.display()
        );
        Some(dir)
    } else {
        tracing::debug!("No embedded frontend assets found");
        None
    }
}

// ════════════════════════════════════════════════════════════════════
//  SessionPort adapter — bridges SessionStore -> SessionPort
// ════════════════════════════════════════════════════════════════════

struct SessionAdapter(Arc<dyn StoragePort>);

#[async_trait]
impl SessionPort for SessionAdapter {
    async fn create(&self, session: Session) -> rusvel_core::error::Result<SessionId> {
        let id = session.id;
        self.0.sessions().put_session(&session).await?;
        Ok(id)
    }
    async fn load(&self, id: &SessionId) -> rusvel_core::error::Result<Session> {
        self.0.sessions().get_session(id).await?.ok_or_else(|| {
            rusvel_core::error::RusvelError::NotFound {
                kind: "session".into(),
                id: id.to_string(),
            }
        })
    }
    async fn save(&self, session: &Session) -> rusvel_core::error::Result<()> {
        self.0.sessions().put_session(session).await
    }
    async fn list(&self) -> rusvel_core::error::Result<Vec<SessionSummary>> {
        self.0.sessions().list_sessions().await
    }
}

fn build_harvest_config(
    config: &TomlConfig,
    profile_path: &std::path::Path,
) -> harvest_engine::HarvestConfig {
    let mut skills: Vec<String> = Vec::new();
    if let Ok(Some(v)) = config.get_value("harvest.skills") {
        if let Some(arr) = v.as_array() {
            skills.extend(
                arr.iter()
                    .filter_map(|x| x.as_str().map(str::trim))
                    .filter(|s| !s.is_empty())
                    .map(String::from),
            );
        } else if let Some(s) = v.as_str() {
            skills.extend(
                s.split(',')
                    .map(str::trim)
                    .filter(|t| !t.is_empty())
                    .map(String::from),
            );
        }
    }
    if skills.is_empty() {
        if let Ok(p) = UserProfile::load(profile_path) {
            skills.extend(p.skills.primary);
            skills.extend(p.skills.secondary);
        }
    }
    if skills.is_empty() {
        skills.push("rust".into());
    }
    harvest_engine::HarvestConfig {
        skills,
        min_budget: None,
    }
}

// ════════════════════════════════════════════════════════════════════
//  Data directory
// ════════════════════════════════════════════════════════════════════

fn rusvel_dir() -> std::path::PathBuf {
    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| ".".into());
    std::path::PathBuf::from(home).join(".rusvel")
}

// ════════════════════════════════════════════════════════════════════
//  Seed data — populate ObjectStore with defaults on first run
// ════════════════════════════════════════════════════════════════════

async fn seed_defaults(storage: &Arc<dyn StoragePort>) -> Result<()> {
    let objects = storage.objects();
    let empty_filter = ObjectFilter::default();

    // ── Seed agents ──────────────────────────────────────────────
    let existing_agents = objects.list("agents", empty_filter.clone()).await?;
    if existing_agents.is_empty() {
        tracing::info!("Seeding default agents...");
        let agents = vec![
            AgentProfile {
                id: AgentProfileId::new(),
                name: "rust-engine".into(),
                role: "Rust backend engineer".into(),
                instructions: "Build RUSVEL engine crates. Follow hexagonal architecture.".into(),
                default_model: ModelRef {
                    provider: ModelProvider::Claude,
                    model: "opus".into(),
                },
                allowed_tools: vec!["read_file".into(), "write_file".into(), "bash".into()],
                capabilities: vec![Capability::CodeAnalysis, Capability::ToolUse],
                budget_limit: None,
                metadata: serde_json::json!({"engine": "code", "department": "Code"}),
            },
            AgentProfile {
                id: AgentProfileId::new(),
                name: "svelte-ui".into(),
                role: "Frontend engineer".into(),
                instructions: "Build SvelteKit 5 pages using RUSVEL design system.".into(),
                default_model: ModelRef {
                    provider: ModelProvider::Claude,
                    model: "sonnet".into(),
                },
                allowed_tools: vec!["read_file".into(), "write_file".into(), "bash".into()],
                capabilities: vec![Capability::CodeAnalysis, Capability::ToolUse],
                budget_limit: None,
                metadata: serde_json::json!({"engine": "code", "department": "Code"}),
            },
            AgentProfile {
                id: AgentProfileId::new(),
                name: "test-writer".into(),
                role: "QA and test engineer".into(),
                instructions: "Write tests for RUSVEL crates and frontend.".into(),
                default_model: ModelRef {
                    provider: ModelProvider::Claude,
                    model: "sonnet".into(),
                },
                allowed_tools: vec!["read_file".into(), "write_file".into(), "bash".into()],
                capabilities: vec![Capability::CodeAnalysis, Capability::ToolUse],
                budget_limit: None,
                metadata: serde_json::json!({"engine": "code", "department": "Code"}),
            },
            AgentProfile {
                id: AgentProfileId::new(),
                name: "content-writer".into(),
                role: "Content strategist and writer".into(),
                instructions: "Draft blog posts, articles, and long-form content.".into(),
                default_model: ModelRef {
                    provider: ModelProvider::Claude,
                    model: "sonnet".into(),
                },
                allowed_tools: vec!["read_file".into(), "web_search".into()],
                capabilities: vec![Capability::ContentCreation],
                budget_limit: None,
                metadata: serde_json::json!({"engine": "content", "department": "Content"}),
            },
            AgentProfile {
                id: AgentProfileId::new(),
                name: "proposal-writer".into(),
                role: "Proposal and business development specialist".into(),
                instructions: "Draft compelling proposals tailored to each gig.".into(),
                default_model: ModelRef {
                    provider: ModelProvider::Claude,
                    model: "opus".into(),
                },
                allowed_tools: vec!["read_file".into(), "web_search".into()],
                capabilities: vec![
                    Capability::ContentCreation,
                    Capability::OpportunityDiscovery,
                ],
                budget_limit: None,
                metadata: serde_json::json!({"engine": "harvest", "department": "Harvest"}),
            },
        ];
        for agent in &agents {
            let val = serde_json::to_value(agent)?;
            objects.put("agents", &agent.id.to_string(), val).await?;
        }
        tracing::info!("Seeded {} default agents", agents.len());
    }

    // ── Seed skills ──────────────────────────────────────────────
    let existing_skills = objects.list("skills", empty_filter.clone()).await?;
    if existing_skills.is_empty() {
        tracing::info!("Seeding default skills...");
        let skills = vec![
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Code Review",
                "description": "Analyze code for bugs, patterns, and improvements",
                "prompt_template": "Review the following code. Identify bugs, anti-patterns, and suggest improvements:\n\n{input}",
                "metadata": {"engine": "code"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Blog Draft",
                "description": "Draft a blog post from a topic and key points",
                "prompt_template": "Write a blog post about: {topic}\n\nKey points to cover:\n{points}\n\nTarget audience: {audience}",
                "metadata": {"engine": "content"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Proposal Draft",
                "description": "Draft a proposal for a freelance opportunity",
                "prompt_template": "Draft a compelling proposal for this opportunity:\n\nTitle: {title}\nDescription: {description}\nBudget: {budget}\n\nHighlight relevant experience and propose a clear plan.",
                "metadata": {"engine": "harvest"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Test Generator",
                "description": "Generate tests for a given Rust module or SvelteKit component",
                "prompt_template": "Generate comprehensive tests for:\n\n{input}\n\nInclude unit tests, edge cases, and integration tests where appropriate.",
                "metadata": {"engine": "code"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Daily Standup",
                "description": "Summarize progress and plan for the day",
                "prompt_template": "Based on recent activity, generate a standup summary:\n- What was accomplished yesterday\n- What is planned for today\n- Any blockers",
                "metadata": {"engine": "forge"}
            }),
        ];
        for skill in &skills {
            let id = skill["id"].as_str().unwrap();
            objects.put("skills", id, skill.clone()).await?;
        }
        tracing::info!("Seeded {} default skills", skills.len());
    }

    // ── Seed rules ───────────────────────────────────────────────
    let existing_rules = objects.list("rules", empty_filter.clone()).await?;
    if existing_rules.is_empty() {
        tracing::info!("Seeding default rules...");
        let rules = vec![
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Hexagonal Architecture",
                "content": "Engines must never import adapter crates. They depend only on rusvel-core port traits. All domain logic flows through ports.",
                "enabled": true,
                "metadata": {"engine": "code"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Human Approval Gate",
                "content": "All content publishing and outreach sending requires human approval before execution. Never auto-publish or auto-send without explicit approval.",
                "enabled": true,
                "metadata": {}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Crate Size Limit",
                "content": "Each crate must stay under 2000 lines. If a crate exceeds this, refactor it into smaller, focused crates with single responsibility.",
                "enabled": true,
                "metadata": {"engine": "code"}
            }),
        ];
        for rule in &rules {
            let id = rule["id"].as_str().unwrap();
            objects.put("rules", id, rule.clone()).await?;
        }
        tracing::info!("Seeded {} default rules", rules.len());
    }

    // ── Seed self-improvement rules ────────────────────────────────
    let existing_rules = objects.list("rules", empty_filter.clone()).await?;
    let si_rule_names = [
        "Hexagonal Boundaries",
        "Crate Size Limit (SI)",
        "Event Sourcing",
        "Metadata Evolution",
        "Test Coverage",
        "Design Tokens",
    ];
    let has_si_rules = existing_rules.iter().any(|r| {
        r.get("name")
            .and_then(|n| n.as_str())
            .is_some_and(|n| si_rule_names.contains(&n))
    });
    if !has_si_rules {
        tracing::info!("Seeding self-improvement rules...");
        let si_rules = vec![
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Hexagonal Boundaries",
                "content": "Engines never import adapter crates. They depend only on rusvel-core port traits. Verify Cargo.toml dependencies of every engine crate.",
                "enabled": true,
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Crate Size Limit (SI)",
                "content": "Each crate must stay under 2000 lines. If a crate exceeds this limit, refactor it into smaller focused crates with single responsibility.",
                "enabled": true,
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Event Sourcing",
                "content": "Every significant state change must emit an event via EventPort. Check that all create/update/delete operations in engines call events.emit().",
                "enabled": true,
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Metadata Evolution",
                "content": "All domain types must carry metadata: serde_json::Value for schema evolution (ADR-007). New fields go in metadata first, then promote to typed fields when stable.",
                "enabled": true,
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Test Coverage",
                "content": "Every new feature must include tests. Run cargo test after every change. Engine tests use mock ports, never real adapters.",
                "enabled": true,
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "Design Tokens",
                "content": "Frontend uses semantic CSS variables (--r-*) from the RUSVEL design system, not raw Tailwind colors. All colors, spacing, and typography must reference design tokens.",
                "enabled": true,
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
        ];
        for rule in &si_rules {
            let id = rule["id"].as_str().unwrap();
            objects.put("rules", id, rule.clone()).await?;
        }
        tracing::info!("Seeded {} self-improvement rules", si_rules.len());
    }

    // ── Seed self-improvement agents ────────────────────────────────
    let si_agent_names = ["arch-reviewer", "si-test-writer", "refactorer", "doc-updater"];
    let has_si_agents = existing_agents.iter().any(|a| {
        a.get("name")
            .and_then(|n| n.as_str())
            .is_some_and(|n| si_agent_names.contains(&n))
    });
    if !has_si_agents {
        tracing::info!("Seeding self-improvement agents...");
        let si_agents = vec![
            AgentProfile {
                id: AgentProfileId::new(),
                name: "arch-reviewer".into(),
                role: "Architecture reviewer".into(),
                instructions: "Review code for hexagonal architecture violations. Check that engine crates never import adapter crates. Verify all domain logic flows through port traits defined in rusvel-core. Check Cargo.toml dependencies of engine crates. Flag any direct adapter usage.".into(),
                default_model: ModelRef {
                    provider: ModelProvider::Claude,
                    model: "opus".into(),
                },
                allowed_tools: vec!["read_file".into(), "bash".into(), "list_files".into()],
                capabilities: vec![Capability::CodeAnalysis],
                budget_limit: None,
                metadata: serde_json::json!({"engine": "code", "department": "Code", "category": "self-improvement"}),
            },
            AgentProfile {
                id: AgentProfileId::new(),
                name: "si-test-writer".into(),
                role: "Test engineer for self-improvement".into(),
                instructions: "Write tests for untested code. Follow existing test patterns in the codebase. Engine tests use mock ports (never real adapters). Include unit tests, edge cases, and integration tests. Run cargo test to verify.".into(),
                default_model: ModelRef {
                    provider: ModelProvider::Claude,
                    model: "sonnet".into(),
                },
                allowed_tools: vec!["read_file".into(), "write_file".into(), "bash".into()],
                capabilities: vec![Capability::CodeAnalysis, Capability::ToolUse],
                budget_limit: None,
                metadata: serde_json::json!({"engine": "code", "department": "Code", "category": "self-improvement"}),
            },
            AgentProfile {
                id: AgentProfileId::new(),
                name: "refactorer".into(),
                role: "Code refactoring specialist".into(),
                instructions: "Refactor code to reduce duplication, improve readability, and enforce size limits. Each crate must stay under 2000 lines. Extract shared logic into helper functions. Maintain hexagonal boundaries during refactoring.".into(),
                default_model: ModelRef {
                    provider: ModelProvider::Claude,
                    model: "sonnet".into(),
                },
                allowed_tools: vec!["read_file".into(), "write_file".into(), "bash".into()],
                capabilities: vec![Capability::CodeAnalysis, Capability::ToolUse],
                budget_limit: None,
                metadata: serde_json::json!({"engine": "code", "department": "Code", "category": "self-improvement"}),
            },
            AgentProfile {
                id: AgentProfileId::new(),
                name: "doc-updater".into(),
                role: "Documentation updater".into(),
                instructions: "Update documentation to match current code state. Read the actual crate structure, count lines, check feature status, and update docs/status/current-state.md and docs/status/gap-analysis.md to reflect reality.".into(),
                default_model: ModelRef {
                    provider: ModelProvider::Claude,
                    model: "haiku".into(),
                },
                allowed_tools: vec!["read_file".into(), "write_file".into(), "bash".into()],
                capabilities: vec![Capability::ContentCreation, Capability::ToolUse],
                budget_limit: None,
                metadata: serde_json::json!({"engine": "code", "department": "Code", "category": "self-improvement"}),
            },
        ];
        for agent in &si_agents {
            let val = serde_json::to_value(agent)?;
            objects.put("agents", &agent.id.to_string(), val).await?;
        }
        tracing::info!("Seeded {} self-improvement agents", si_agents.len());
    }

    // ── Seed self-improvement skills ────────────────────────────────
    let si_skill_names = [
        "/analyze-architecture",
        "/check-crate-sizes",
        "/enforce-rules",
        "/self-review",
        "/update-docs",
    ];
    let existing_skills_all = objects.list("skills", empty_filter.clone()).await?;
    let has_si_skills = existing_skills_all.iter().any(|s| {
        s.get("name")
            .and_then(|n| n.as_str())
            .is_some_and(|n| si_skill_names.contains(&n))
    });
    if !has_si_skills {
        tracing::info!("Seeding self-improvement skills...");
        let si_skills = vec![
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "/analyze-architecture",
                "description": "Scan all engine crates for hexagonal architecture violations",
                "prompt_template": "Analyze the RUSVEL codebase for architecture violations:\n\n1. Scan all engine crates (forge-engine, code-engine, harvest-engine, content-engine, gtm-engine, finance-engine, product-engine, growth-engine, distro-engine, legal-engine, support-engine, infra-engine)\n2. Check each engine's Cargo.toml — engines must ONLY depend on rusvel-core, never on adapter crates (rusvel-db, rusvel-llm, rusvel-embed, rusvel-vector, etc.)\n3. Check source code for any direct imports of adapter types\n4. Verify all domain logic flows through port traits\n5. List all violations found\n6. Suggest fixes for each violation",
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "/check-crate-sizes",
                "description": "List all crates with line counts and flag any over 2000 lines",
                "prompt_template": "Check all RUSVEL crate sizes:\n\n1. For each crate in crates/, count total lines of Rust code (*.rs files)\n2. List all crates sorted by size (largest first)\n3. Flag any crate exceeding 2000 lines with a warning\n4. For flagged crates, suggest how to split them into smaller focused crates\n5. Show the total line count across all crates\n\nRun: find crates/ -name '*.rs' | xargs wc -l | sort -rn",
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "/enforce-rules",
                "description": "Load all enabled rules and verify each against the codebase",
                "prompt_template": "Enforce all enabled RUSVEL rules:\n\n1. Load all rules from the rules store (GET /api/rules)\n2. For each enabled rule, verify compliance against the actual codebase:\n   - Hexagonal boundaries: check engine Cargo.toml deps\n   - Crate size limits: count lines per crate\n   - Event sourcing: check engines emit events on state changes\n   - Metadata evolution: verify domain types have metadata field\n   - Test coverage: check for test modules in each crate\n   - Design tokens: check frontend for raw color values vs CSS variables\n3. Report violations with file paths and line numbers\n4. Prioritize fixes by severity",
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "/self-review",
                "description": "Run tests, check warnings, identify and implement the easiest improvement",
                "prompt_template": "Perform a self-review of RUSVEL:\n\n1. Run `cargo test` and report results (pass/fail count, any failures)\n2. Run `cargo build 2>&1` and check for warnings\n3. Read docs/status/gap-analysis.md to understand known gaps\n4. Read docs/status/current-state.md for current status\n5. Identify the top 3 improvements that would have the most impact\n6. Implement the easiest one (the one requiring the fewest changes)\n7. Run `cargo test` again to verify the fix\n8. Report what was done",
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
            serde_json::json!({
                "id": uuid::Uuid::now_v7().to_string(),
                "name": "/update-docs",
                "description": "Update docs/status/current-state.md to match actual code reality",
                "prompt_template": "Update RUSVEL documentation to match current code state:\n\n1. Read the current crate structure: ls crates/\n2. For each crate, check: lines of code, public API, test count\n3. Read the current docs/status/current-state.md\n4. Update it with accurate information:\n   - Which crates exist and their sizes\n   - Which features are implemented vs stubbed\n   - Which ports have real adapters vs placeholders\n   - Frontend status (pages, components)\n5. Also update docs/status/gap-analysis.md with current gaps\n6. Ensure all dates and version references are current",
                "metadata": {"engine": "code", "category": "self-improvement"}
            }),
        ];
        for skill in &si_skills {
            let id = skill["id"].as_str().unwrap();
            objects.put("skills", id, skill.clone()).await?;
        }
        tracing::info!("Seeded {} self-improvement skills", si_skills.len());
    }

    // ── Seed self-improvement workflow ───────────────────────────────
    let existing_workflows = objects.list("workflows", empty_filter.clone()).await?;
    let has_si_workflow = existing_workflows.iter().any(|w| {
        w.get("name")
            .and_then(|n| n.as_str())
            .is_some_and(|n| n == "self-improve")
    });
    if !has_si_workflow {
        tracing::info!("Seeding self-improvement workflow...");
        let workflow = serde_json::json!({
            "id": uuid::Uuid::now_v7().to_string(),
            "name": "self-improve",
            "description": "Automated self-improvement cycle: review architecture, write tests, refactor issues, update docs",
            "steps": [
                {
                    "agent": "arch-reviewer",
                    "prompt": "Analyze the codebase for architecture violations and code quality issues. Check all engine crates for adapter imports. Verify port trait usage. List all violations with severity.",
                    "order": 1
                },
                {
                    "agent": "si-test-writer",
                    "prompt": "Check test coverage across all crates. Identify untested critical paths. Write tests for any untested code, following existing test patterns. Run cargo test to verify.",
                    "order": 2
                },
                {
                    "agent": "refactorer",
                    "prompt": "Fix the top issue found by the architecture review. Refactor to maintain hexagonal boundaries, reduce duplication, and keep crates under 2000 lines. Run cargo test after changes.",
                    "order": 3
                },
                {
                    "agent": "doc-updater",
                    "prompt": "Update docs/status/current-state.md with the current state of the codebase. Reflect any changes made by previous steps. Ensure accuracy of crate sizes, feature status, and known gaps.",
                    "order": 4
                }
            ],
            "metadata": {"category": "self-improvement", "engine": "code"}
        });
        let id = workflow["id"].as_str().unwrap().to_string();
        objects.put("workflows", &id, workflow).await?;
        tracing::info!("Seeded self-improvement workflow");
    }

    Ok(())
}

// ════════════════════════════════════════════════════════════════════
//  Knowledge ingestion — seed RUSVEL's own docs into vector store
// ════════════════════════════════════════════════════════════════════

/// Chunk text into paragraphs (split on double newlines), filtering out
/// very short chunks that would produce low-quality embeddings.
fn chunk_into_paragraphs(text: &str, source: &str) -> Vec<(String, String)> {
    text.split("\n\n")
        .map(str::trim)
        .filter(|p| p.len() >= 50) // skip tiny fragments
        .enumerate()
        .map(|(i, para)| {
            let id = format!("{source}::chunk-{i}");
            (id, para.to_string())
        })
        .collect()
}

/// Ingest RUSVEL's own documentation into the knowledge base on first run.
///
/// Reads key project files, chunks them into paragraphs, embeds each chunk,
/// and stores them in the vector store. This makes all department chats
/// aware of RUSVEL's own architecture, conventions, and current state.
async fn seed_knowledge(
    embedding: &Arc<dyn EmbeddingPort>,
    vector_store: &Arc<dyn VectorStorePort>,
    data_dir: &std::path::Path,
) -> Result<()> {
    // Check if knowledge is already populated
    let count = vector_store.count().await.unwrap_or(0);
    if count > 0 {
        tracing::debug!("Knowledge base already has {count} entries, skipping seed");
        return Ok(());
    }

    tracing::info!("Seeding knowledge base with RUSVEL docs...");

    // Resolve project root (two levels up from crates/rusvel-app/)
    // We try the current working directory first, then fall back to
    // a relative path from the data directory.
    let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));

    // Collect (file_path, source_label) pairs to ingest
    let doc_files: Vec<(PathBuf, &str)> = vec![
        (project_root.join("CLAUDE.md"), "CLAUDE.md"),
        (
            project_root.join("docs/design/architecture-v2.md"),
            "architecture-v2.md",
        ),
        (
            project_root.join("docs/design/decisions.md"),
            "decisions.md",
        ),
        (
            project_root.join("docs/status/current-state.md"),
            "current-state.md",
        ),
        (
            project_root.join("docs/status/gap-analysis.md"),
            "gap-analysis.md",
        ),
        (data_dir.join("profile.toml"), "profile.toml"),
    ];

    let mut total_chunks = 0usize;

    for (path, source) in &doc_files {
        let content = match std::fs::read_to_string(path) {
            Ok(c) => c,
            Err(e) => {
                tracing::debug!("Skipping {source}: {e}");
                continue;
            }
        };

        if content.trim().is_empty() {
            tracing::debug!("Skipping {source}: empty file");
            continue;
        }

        let chunks = chunk_into_paragraphs(&content, source);
        if chunks.is_empty() {
            tracing::debug!("Skipping {source}: no substantial paragraphs");
            continue;
        }

        // Batch-embed all chunks for this file
        let texts: Vec<&str> = chunks.iter().map(|(_, text)| text.as_str()).collect();
        let embeddings = match embedding.embed(&texts).await {
            Ok(e) => e,
            Err(e) => {
                tracing::warn!("Failed to embed {source}: {e}");
                continue;
            }
        };

        // Store each chunk
        for ((id, text), emb) in chunks.iter().zip(embeddings.into_iter()) {
            let metadata = serde_json::json!({
                "source": source,
                "type": "project-doc",
                "category": "self-knowledge",
            });
            if let Err(e) = vector_store.upsert(id, text, emb, metadata).await {
                tracing::warn!("Failed to store chunk {id}: {e}");
            } else {
                total_chunks += 1;
            }
        }

        tracing::debug!("Ingested {source}: {} chunks", chunks.len());
    }

    tracing::info!("Knowledge base seeded with {total_chunks} chunks from {} docs", doc_files.len());
    Ok(())
}

// ════════════════════════════════════════════════════════════════════
//  First-run wizard — interactive onboarding via cliclack
// ════════════════════════════════════════════════════════════════════

async fn first_run_wizard(
    data_dir: &std::path::Path,
    sessions: &Arc<dyn SessionPort>,
) -> Result<Option<UserProfile>> {
    use cliclack::{confirm, input, intro, outro_note, select};

    intro("Welcome to RUSVEL — Your AI-Powered Virtual Agency")?;

    // Detect LLM availability
    let ollama_ok = reqwest::Client::new()
        .get("http://localhost:11434/api/tags")
        .timeout(std::time::Duration::from_secs(2))
        .send()
        .await
        .is_ok();
    if ollama_ok {
        cliclack::log::success("Ollama detected at localhost:11434")?;
    } else {
        cliclack::log::warning("Ollama not running — will use Claude CLI as fallback")?;
    }

    // User identity
    let name: String = input("What's your name?")
        .placeholder("e.g. Mehdi")
        .required(true)
        .interact()?;

    let role: String = input("What's your role?")
        .placeholder("e.g. Solo founder, Developer")
        .default_input("Solo founder")
        .interact()?;

    // Create profile.toml
    let profile_content = format!(
        r#"[identity]
name = "{name}"
role = "{role}"
tagline = ""

[skills]
primary = []
secondary = []

[products]
names = []
description = ""

[mission]
vision = ""
values = []

[preferences]
style = "direct"
"#
    );
    std::fs::write(data_dir.join("profile.toml"), &profile_content)?;
    cliclack::log::success(format!("Profile saved for {name}"))?;

    // Create first session
    let create_session: bool = confirm("Create your first session?")
        .initial_value(true)
        .interact()?;

    if create_session {
        let session_name: String = input("Session name")
            .placeholder("e.g. my-startup")
            .default_input("default")
            .interact()?;

        let kind_idx: &str = select("Session type")
            .item("Project", "Project", "For building a product or app")
            .item("Lead", "Lead", "For tracking a freelance opportunity")
            .item(
                "ContentCampaign",
                "Content Campaign",
                "For a content initiative",
            )
            .item("General", "General", "For everything else")
            .interact()?;

        let kind = match kind_idx {
            "Project" => SessionKind::Project,
            "Lead" => SessionKind::Lead,
            "ContentCampaign" => SessionKind::ContentCampaign,
            _ => SessionKind::General,
        };

        let now = Utc::now();
        let session = Session {
            id: SessionId::new(),
            name: session_name.clone(),
            kind,
            tags: vec![],
            config: SessionConfig::default(),
            created_at: now,
            updated_at: now,
            metadata: serde_json::json!({}),
        };
        let id = sessions.create(session).await?;

        // Save as active session
        let active_path = data_dir.join("active_session");
        std::fs::write(&active_path, id.to_string())?;
        cliclack::log::success(format!("Session \"{session_name}\" created"))?;
    }

    outro_note(
        "Ready!",
        "Next steps:\n  → Open http://localhost:3000 in your browser\n  → Or run: rusvel forge mission today",
    )?;

    // Load and return the profile we just created
    Ok(UserProfile::load(data_dir.join("profile.toml")).ok())
}

// ════════════════════════════════════════════════════════════════════
//  Main
// ════════════════════════════════════════════════════════════════════

#[tokio::main]
async fn main() -> Result<()> {
    // 1. Tracing
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();

    // 2. Data directory
    let data_dir = rusvel_dir();
    std::fs::create_dir_all(&data_dir)?;

    // 3. Concrete adapters
    let db: Arc<Database> = Arc::new(Database::open(data_dir.join("rusvel.db"))?);
    let config = Arc::new(TomlConfig::load(data_dir.join("config.toml"))?);
    let llm: Arc<dyn rusvel_core::ports::LlmPort> = Arc::new(ClaudeCliProvider::max_subscription());
    let events = Arc::new(EventBus::new(
        db.clone() as Arc<dyn rusvel_core::ports::EventStore>
    ));
    let memory: Arc<dyn rusvel_core::ports::MemoryPort> = Arc::new(MemoryStore::open(
        data_dir.join("memory.db").to_str().unwrap_or("memory.db"),
    )?);
    let tool_registry = Arc::new(ToolRegistry::new());
    rusvel_builtin_tools::register_all(&tool_registry).await;
    let tools: Arc<dyn rusvel_core::ports::ToolPort> = tool_registry.clone();
    rusvel_builtin_tools::tool_search::register(&tool_registry, tools.clone()).await;
    // Single SQLite-backed queue: worker, ContentCalendar, ForgeEngine, and
    // GET/POST /api/approvals all use this same `Database` as `JobPort` (ADR-003, ADR-008).
    let jobs: Arc<dyn JobPort> = db.clone() as Arc<dyn JobPort>;
    let jobs_for_worker = jobs.clone();
    // auth is now created below and passed to boot_departments
    let sessions: Arc<dyn SessionPort> =
        Arc::new(SessionAdapter(db.clone() as Arc<dyn StoragePort>));
    let agent_runtime = Arc::new(AgentRuntime::new(
        llm.clone(),
        tools.clone(),
        memory.clone(),
    ));
    let agent: Arc<dyn rusvel_core::ports::AgentPort> = agent_runtime.clone();
    let auth: Arc<dyn rusvel_core::ports::AuthPort> = Arc::new(InMemoryAuthAdapter::from_env());

    // 3b. Boot departments (ADR-014)
    let departments = boot::installed_departments();
    let dept_registry = boot::boot_departments(
        &departments,
        agent_runtime.clone(),
        events.clone(),
        db.clone() as Arc<dyn StoragePort>,
        jobs.clone(),
        memory.clone(),
        sessions.clone(),
        config.clone(),
        auth.clone(),
        None, // embedding — initialized later for API surface only
        None, // vector_store — initialized later for API surface only
    )
    .await?;
    tracing::info!(
        "ADR-014 boot: {} departments registered",
        dept_registry.departments.len()
    );

    // 4. Build engines (legacy path — kept for backward compat during migration)
    let agent_for_content = agent.clone();
    let agent_for_harvest = agent.clone();
    let agent_for_flow = agent.clone();
    let jobs_for_engines = jobs.clone();

    let forge = Arc::new(ForgeEngine::new(
        agent,
        events.clone(),
        memory.clone(),
        db.clone() as Arc<dyn StoragePort>,
        jobs.clone(),
        sessions.clone(),
        config.clone(),
    ));

    // 4b. Domain engines (Code, Content, Harvest)
    let code_engine = Arc::new(code_engine::CodeEngine::new(
        db.clone() as Arc<dyn StoragePort>,
        events.clone(),
    ));
    let content_engine = Arc::new(content_engine::ContentEngine::new(
        db.clone() as Arc<dyn StoragePort>,
        events.clone(),
        agent_for_content,
        jobs_for_engines,
    ));
    content_engine.register_platform(Arc::new(
        content_engine::adapters::linkedin::LinkedInAdapter::new(config.clone()),
    ));
    content_engine.register_platform(Arc::new(
        content_engine::adapters::twitter::TwitterAdapter::new(config.clone()),
    ));
    content_engine.register_platform(Arc::new(
        content_engine::adapters::devto::DevToAdapter::new(config.clone()),
    ));
    let harvest_cfg = build_harvest_config(config.as_ref(), &data_dir.join("profile.toml"));
    let harvest_engine = Arc::new(
        harvest_engine::HarvestEngine::new(db.clone() as Arc<dyn StoragePort>)
            .with_events(events.clone())
            .with_agent(agent_for_harvest)
            .with_config(harvest_cfg),
    );
    let config_port: Arc<dyn ConfigPort> = config.clone();
    let deploy: Arc<dyn DeployPort> = Arc::new(rusvel_deploy::FlyDeployPort::new(config_port));
    let terminal_for_flow: Arc<dyn rusvel_core::ports::TerminalPort> =
        Arc::new(TerminalManager::new(events.clone(), db.clone()));
    let flow_engine = Arc::new(flow_engine::FlowEngine::new(
        db.clone() as Arc<dyn StoragePort>,
        events.clone(),
        agent_for_flow,
        Some(terminal_for_flow.clone()),
    ));
    tracing::info!("Domain engines initialized: Code, Content, Harvest, Flow");

    // 4c. Register engine tools into the tool registry
    rusvel_engine_tools::register_harvest_tools(&tool_registry, harvest_engine.clone()).await;
    rusvel_engine_tools::register_content_tools(&tool_registry, content_engine.clone()).await;
    rusvel_engine_tools::register_code_tools(&tool_registry, code_engine.clone()).await;
    tracing::info!("Engine tools registered: harvest(5), content(5), code(2)");

    // 5. Seed default data (agents, skills, rules) on first run
    let storage_ref: Arc<dyn StoragePort> = db.clone() as Arc<dyn StoragePort>;
    seed_defaults(&storage_ref).await?;

    // 6. Spawn background job queue worker
    let code_engine_worker = code_engine.clone();
    let content_engine_worker = content_engine.clone();
    let harvest_engine_worker = harvest_engine.clone();
    let _job_worker = tokio::spawn(async move {
        let job_port = jobs_for_worker;
        loop {
            match job_port.dequeue(&[]).await {
                Ok(Some(job)) => {
                    // Skip jobs awaiting human approval (ADR-008)
                    if job.status == JobStatus::AwaitingApproval {
                        tracing::debug!(job_id = %job.id, "Skipping job awaiting approval");
                        tokio::time::sleep(Duration::from_secs(5)).await;
                        continue;
                    }

                    let job_id = job.id;
                    tracing::info!(job_id = %job_id, kind = ?job.kind, "Processing job");

                    let job_finish: std::result::Result<
                        Option<JobResult>,
                        rusvel_core::error::RusvelError,
                    > = match job.kind {
                        JobKind::CodeAnalyze => {
                            let path_str = job
                                .payload
                                .get("path")
                                .and_then(|v| v.as_str())
                                .unwrap_or(".");
                            match code_engine_worker
                                .analyze(std::path::Path::new(path_str))
                                .await
                            {
                                Ok(analysis) => Ok(Some(JobResult {
                                    output: serde_json::to_value(&analysis).unwrap_or_default(),
                                    metadata: serde_json::json!({"engine": "code"}),
                                })),
                                Err(e) => {
                                    tracing::error!(job_id = %job_id, error = %e, "Code analyze failed");
                                    Err(e)
                                }
                            }
                        }
                        JobKind::ContentPublish => {
                            let sid = job.session_id;
                            let content_id_str = job
                                .payload
                                .get("content_id")
                                .and_then(|v| v.as_str())
                                .unwrap_or_default();
                            let platform_str = job
                                .payload
                                .get("platform")
                                .and_then(|v| v.as_str())
                                .unwrap_or_default();
                            if let (Ok(cid), Ok(platform)) = (
                                content_id_str
                                    .parse::<uuid::Uuid>()
                                    .map(rusvel_core::id::ContentId::from_uuid),
                                serde_json::from_value::<Platform>(serde_json::json!(platform_str)),
                            ) {
                                match content_engine_worker.publish(&sid, cid, platform).await {
                                    Ok(result) => Ok(Some(JobResult {
                                        output: serde_json::to_value(&result).unwrap_or_default(),
                                        metadata: serde_json::json!({"engine": "content"}),
                                    })),
                                    Err(e) => {
                                        tracing::error!(job_id = %job_id, error = %e, "Content publish failed");
                                        Err(e)
                                    }
                                }
                            } else {
                                Ok(Some(JobResult {
                                    output: serde_json::json!({"error": "invalid job payload: missing content_id or platform"}),
                                    metadata: serde_json::json!({"engine": "content"}),
                                }))
                            }
                        }
                        JobKind::HarvestScan => {
                            let sid = job.session_id;
                            match harvest_engine_worker
                                .scan(&sid, &harvest_engine::source::MockSource::new())
                                .await
                            {
                                Ok(opportunities) => Ok(Some(JobResult {
                                    output: serde_json::json!({
                                        "count": opportunities.len(),
                                        "ids": opportunities.iter().map(|o| o.id.to_string()).collect::<Vec<_>>(),
                                    }),
                                    metadata: serde_json::json!({"engine": "harvest"}),
                                })),
                                Err(e) => {
                                    tracing::error!(job_id = %job_id, error = %e, "Harvest scan failed");
                                    Err(e)
                                }
                            }
                        }
                        JobKind::ProposalDraft => {
                            let sid = job.session_id;
                            if let Some(v) = job.metadata.get("approval_pending_result") {
                                match serde_json::from_value::<JobResult>(v.clone()) {
                                    Ok(result) => Ok(Some(result)),
                                    Err(e) => Err(rusvel_core::error::RusvelError::Serialization(
                                        e.to_string(),
                                    )),
                                }
                            } else if let Some(opp) = job
                                .payload
                                .get("opportunity_id")
                                .and_then(|x| x.as_str())
                            {
                                let profile = job
                                    .payload
                                    .get("profile")
                                    .and_then(|x| x.as_str())
                                    .unwrap_or("");
                                match harvest_engine_worker
                                    .generate_proposal(&sid, opp, profile)
                                    .await
                                {
                                    Ok(proposal) => {
                                        let job_result = JobResult {
                                            output: serde_json::to_value(&proposal)
                                                .unwrap_or_default(),
                                            metadata: serde_json::json!({"engine": "harvest"}),
                                        };
                                        match job_port
                                            .hold_for_approval(&job_id, job_result)
                                            .await
                                        {
                                            Ok(()) => Ok(None),
                                            Err(e) => Err(e),
                                        }
                                    }
                                    Err(e) => {
                                        tracing::error!(job_id = %job_id, error = %e, "Proposal draft failed");
                                        Err(e)
                                    }
                                }
                            } else {
                                Err(rusvel_core::error::RusvelError::Validation(
                                    "ProposalDraft job missing opportunity_id".into(),
                                ))
                            }
                        }
                        JobKind::OutreachSend => {
                            // GTM engine not yet wired — keep as placeholder
                            tracing::info!(job_id = %job_id, "OutreachSend: GTM engine not yet wired");
                            Ok(Some(JobResult {
                                output: serde_json::json!({"action": "outreach_send", "status": "engine_not_wired"}),
                                metadata: serde_json::json!({}),
                            }))
                        }
                        _ => {
                            tracing::warn!(job_id = %job_id, kind = ?job.kind, "Unknown job kind");
                            Ok(Some(JobResult {
                                output: serde_json::json!({"action": "unknown", "kind": format!("{:?}", job.kind)}),
                                metadata: serde_json::json!({}),
                            }))
                        }
                    };

                    match job_finish {
                        Ok(Some(job_result)) => {
                            if let Err(e) = job_port.complete(&job_id, job_result).await {
                                tracing::error!(job_id = %job_id, error = %e, "Failed to mark job complete");
                            }
                        }
                        Ok(None) => {}
                        Err(error) => {
                            if let Err(e) = job_port.fail(&job_id, error.to_string()).await {
                                tracing::error!(job_id = %job_id, error = %e, "Failed to mark job failed");
                            }
                        }
                    }
                }
                Ok(None) => {
                    // No jobs available, sleep before polling again
                }
                Err(e) => {
                    tracing::error!(error = %e, "Error dequeuing job");
                }
            }
            tokio::time::sleep(Duration::from_secs(5)).await;
        }
    });
    tracing::info!("Job queue worker started");

    // 7. Parse CLI early so we can skip wizard for subcommands
    let cli = Cli::parse();

    // 8. Load user profile — run first-run wizard if no profile exists
    let profile_path = data_dir.join("profile.toml");
    let profile = if profile_path.exists() {
        match UserProfile::load(&profile_path) {
            Ok(p) => {
                tracing::info!("Loaded profile for {}", p.identity.name);
                Some(p)
            }
            Err(e) => {
                tracing::warn!("No profile loaded ({}): {e}", profile_path.display());
                None
            }
        }
    } else if cli.command.is_none() && !cli.mcp && std::io::stdin().is_terminal() {
        // First run + interactive terminal + no subcommand → run wizard
        match first_run_wizard(&data_dir, &sessions).await {
            Ok(p) => p,
            Err(e) => {
                tracing::warn!("Wizard skipped: {e}");
                None
            }
        }
    } else {
        None
    };

    // 9. Dispatch
    let storage_port: Arc<dyn StoragePort> = db.clone() as Arc<dyn StoragePort>;
    if cli.command.is_some() {
        // Subcommand present -> CLI handler (includes `shell` command)
        let engine_refs = rusvel_cli::departments::EngineRefs {
            code: Some(code_engine.clone()),
            content: Some(content_engine.clone()),
            harvest: Some(harvest_engine.clone()),
        };
        rusvel_cli::run(cli, forge.clone(), sessions.clone(), storage_port, engine_refs).await?;
    } else if cli.tui {
        // --tui flag: launch TUI dashboard
        tracing::info!("Launching TUI dashboard...");
        let session_name = if crate::rusvel_dir().join("active_session").exists() {
            {
                std::fs::read_to_string(rusvel_dir().join("active_session"))
                    .unwrap_or_default()
                    .trim()
                    .to_string()
            }
        } else {
            "(no session)".into()
        };

        // Load data from storage for the dashboard
        let objects = storage_port.objects();
        let filter = rusvel_core::domain::ObjectFilter::default();

        let goals_json = objects
            .list("goals", filter.clone())
            .await
            .unwrap_or_default();
        let goals: Vec<rusvel_core::domain::Goal> = goals_json
            .into_iter()
            .filter_map(|v| serde_json::from_value(v).ok())
            .collect();

        let tasks_json = objects
            .list("tasks", filter.clone())
            .await
            .unwrap_or_default();
        let tasks: Vec<rusvel_core::domain::Task> = tasks_json
            .into_iter()
            .filter_map(|v| serde_json::from_value(v).ok())
            .collect();

        let opps_json = objects
            .list("opportunities", filter.clone())
            .await
            .unwrap_or_default();
        let opportunities: Vec<rusvel_core::domain::Opportunity> = opps_json
            .into_iter()
            .filter_map(|v| serde_json::from_value(v).ok())
            .collect();

        let events_json = objects
            .list(
                "events",
                rusvel_core::domain::ObjectFilter {
                    limit: Some(50),
                    ..Default::default()
                },
            )
            .await
            .unwrap_or_default();
        let recent_events: Vec<rusvel_core::domain::Event> = events_json
            .into_iter()
            .filter_map(|v| serde_json::from_value(v).ok())
            .collect();

        let tui_data = rusvel_tui::TuiData {
            session_name,
            goals,
            tasks,
            opportunities,
            recent_events,
        };
        rusvel_tui::run_tui(tui_data).await?;
    } else if cli.mcp {
        // --mcp flag: start MCP server over stdio (JSON-RPC)
        tracing::info!("Starting MCP server on stdio...");
        let mcp = Arc::new(RusvelMcp::new(forge.clone(), sessions.clone()));
        rusvel_mcp::run_stdio(mcp)
            .await
            .map_err(|e| anyhow::anyhow!("{e}"))?;
    } else {
        // Default: start the API web server with graceful shutdown
        // Use registry generated by department boot (ADR-014)
        let registry = dept_registry;

        // Initialize embedding + vector store for RAG (graceful if either fails)
        let (embedding, embed_dims): (Option<Arc<dyn rusvel_core::ports::EmbeddingPort>>, usize) =
            match FastEmbedAdapter::new() {
                Ok(adapter) => {
                    let dims = adapter.dimensions();
                    tracing::info!(
                        "Embedding adapter ready ({}, {}d)",
                        adapter.model_name(),
                        dims
                    );
                    (Some(Arc::new(adapter)), dims)
                }
                Err(e) => {
                    tracing::warn!("Embedding adapter unavailable: {e}");
                    (None, 384)
                }
            };

        let vector_store: Option<Arc<dyn rusvel_core::ports::VectorStorePort>> = {
            let lance_path = data_dir.join("knowledge.lance");
            let lance_str = lance_path.to_string_lossy().to_string();
            match LanceVectorStore::open(&lance_str, embed_dims).await {
                Ok(vs) => {
                    tracing::info!("Vector store ready at {}", lance_path.display());
                    Some(Arc::new(vs))
                }
                Err(e) => {
                    tracing::warn!("Vector store unavailable: {e}");
                    None
                }
            }
        };

        // Knowledge seeding is on-demand via POST /api/system/ingest-docs (not at startup)

        let _kb_indexer = rusvel_api::knowledge::spawn_knowledge_indexer(
            events.clone(),
            memory.clone(),
            db.clone() as Arc<dyn StoragePort>,
            embedding.clone(),
            vector_store.clone(),
        );

        let state = AppState {
            forge: forge.clone(),
            code_engine: Some(code_engine.clone()),
            content_engine: Some(content_engine.clone()),
            harvest_engine: Some(harvest_engine.clone()),
            flow_engine: Some(flow_engine.clone()),
            sessions: sessions.clone(),
            events: events.clone(),
            jobs: jobs.clone(),
            database: db.clone(),
            storage: db.clone() as Arc<dyn StoragePort>,
            profile,
            registry,
            embedding,
            vector_store,
            memory: memory.clone(),
            deploy: Some(deploy),
            agent_runtime: agent_runtime.clone(),
            tools: tools.clone(),
            terminal: Some(terminal_for_flow.clone()),
        };

        // Look for frontend build in known locations (filesystem first)
        let frontend_dir = [
            PathBuf::from("frontend/build"), // dev: run from repo root
            data_dir.join("frontend"),       // installed: ~/.rusvel/frontend
            std::env::current_exe() // next to binary
                .unwrap_or_default()
                .parent()
                .unwrap_or(std::path::Path::new("."))
                .join("frontend"),
        ]
        .into_iter()
        .find(|p| p.join("index.html").exists())
        // Fallback: extract embedded assets (rust-embed) to temp dir
        .or_else(|| {
            tracing::info!("No frontend build on disk, trying embedded assets...");
            extract_embedded_frontend()
        });

        if let Some(ref dir) = frontend_dir {
            tracing::info!("Serving frontend from {}", dir.display());
        } else {
            tracing::warn!("No frontend found — UI will not be available");
        }
        let router = rusvel_api::build_router_with_frontend(state, frontend_dir);
        let addr: SocketAddr = "127.0.0.1:3000".parse()?;
        tracing::info!("RUSVEL starting on http://{addr}");

        let server = rusvel_api::start_server(router, addr);
        let shutdown = tokio::signal::ctrl_c();

        tokio::select! {
            result = server => result.map_err(|e| anyhow::anyhow!("{e}"))?,
            _ = shutdown => tracing::info!("Shutdown signal received, exiting"),
        }
    }

    Ok(())
}
