//! Help API handler — AI-powered contextual help for RUSVEL.
//!
//! `POST /api/help` accepts a question and streams a help response via SSE.
//! Uses RUSVEL's own documentation as context for accurate answers.

use std::convert::Infallible;
use std::sync::Arc;

use axum::Json;
use axum::extract::State;
use axum::http::StatusCode;
use axum::response::sse::{Event, KeepAlive, Sse};
use futures::stream::Stream;
use serde::Deserialize;
use tokio_stream::StreamExt;
use tokio_stream::wrappers::ReceiverStream;

use rusvel_llm::stream::{ClaudeCliStreamer, StreamEvent};

use crate::AppState;

#[derive(Debug, Deserialize)]
pub struct HelpRequest {
    pub question: String,
    #[serde(default)]
    pub context: Option<String>, // e.g. "forge", "code" — which department the user is in
}

const HELP_SYSTEM_PROMPT: &str = r#"You are RUSVEL's built-in help assistant. Answer questions about how RUSVEL works.

RUSVEL is an AI-powered virtual agency for solo builders. Key concepts:

## Architecture
- Hexagonal (ports & adapters). Engines depend only on port traits, never adapter crates.
- 12 departments: Forge (mission planning), Code (codebase intelligence), Content (writing), Harvest (opportunity discovery), GTM (go-to-market), Finance (ledger/runway), Product (roadmap), Growth (KPIs/funnels), Distro (SEO/marketplace), Legal (contracts/compliance), Support (tickets/NPS), Infra (deploy/monitoring).

## Sessions
- Sessions are workspaces. Each has its own goals, events, and conversations.
- Types: Project, Lead, ContentCampaign, General.
- Create via sidebar "+ New Session" or CLI: `rusvel session create <name>`

## Key Features
- **Goals**: Set in Forge department. Track progress toward objectives.
- **Daily Plans**: Generated by AI based on goals and recent activity. Run from Forge or CLI.
- **Cross-engine pipeline (S-042)**: `POST /api/forge/pipeline` with JSON `{"session_id": "<uuid>"}` and optional `def` (`steps`, `proposal_profile`, `draft_topic`, `draft_kind`). Runs Harvest scan → score → propose → Content draft; returns a `FlowExecution` with `id`, `status`, `node_results` (same shape as flow executions). Errors include `execution_id` in pipeline events when a step fails.
- **Agents**: AI personas with specific roles (rust-engine, content-writer, etc.). CRUD in each department panel.
- **Skills**: Reusable prompt templates. Can be applied to agents.
- **Rules**: Constraints injected into agent system prompts (e.g. "follow hexagonal architecture").
- **Workflows**: Chain agents together (Sequential, Parallel, Loop, Graph patterns).
- **MCP Servers**: Extend agent capabilities via Model Context Protocol.
- **Hooks**: Automate actions on lifecycle events.

## CLI Commands
- `rusvel` — Start API server on :3000
- `rusvel session create <name>` — Create a session
- `rusvel session list` — List sessions
- `rusvel forge mission today` — Generate daily plan
- `rusvel forge mission goals` — List goals
- `rusvel forge mission goal add <title>` — Add a goal
- `rusvel forge mission review --period week` — Generate review

## UI Navigation
- **Cmd+K** — Open command palette for quick navigation
- Each department has: Chat (right), Panel (left) with tabs: Actions, Agents, Workflows, Skills, Rules, MCP, Hooks, Dirs, Events
- **Dashboard** — Overview of goals and events for active session

Be concise and helpful. If the user asks about a feature that doesn't exist yet, say so honestly.
"#;

/// `POST /api/help` — stream a help response via SSE.
pub async fn help_handler(
    State(_state): State<Arc<AppState>>,
    Json(body): Json<HelpRequest>,
) -> Result<Sse<impl Stream<Item = Result<Event, Infallible>>>, (StatusCode, String)> {
    let mut prompt_parts = vec![format!("<system>\n{HELP_SYSTEM_PROMPT}\n</system>")];

    if let Some(ctx) = &body.context {
        prompt_parts.push(format!("The user is currently in the {ctx} department."));
    }

    prompt_parts.push(body.question.clone());
    let prompt = prompt_parts.join("\n\n");

    let streamer = ClaudeCliStreamer::new();
    let rx = streamer.stream(&prompt);

    let stream = ReceiverStream::new(rx).map(move |event| {
        let sse_event = match &event {
            StreamEvent::Delta { text } => Event::default()
                .event("delta")
                .data(serde_json::json!({"text": text}).to_string()),
            StreamEvent::Done {
                full_text,
                cost_usd,
            } => Event::default().event("done").data(
                serde_json::json!({
                    "text": full_text,
                    "cost_usd": cost_usd,
                })
                .to_string(),
            ),
            StreamEvent::Error { message } => Event::default()
                .event("error")
                .data(serde_json::json!({"message": message}).to_string()),
        };
        Ok(sse_event)
    });

    Ok(Sse::new(stream).keep_alive(KeepAlive::default()))
}
